# Generated by Django 5.1.7 on 2025-04-04 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('avatar', models.ImageField(blank=True, default='', upload_to='avatars/%Y/%m')),
                ('major', models.CharField(blank=True, default='', max_length=100)),
                ('resume', models.TextField(blank=True, default='')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, '未设置'), (1, '访客'), (2, '编辑'), (10, '管理员')], default=0)),
                ('title', models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '教授'), (2, '研究员'), (3, '副教授'), (4, '副研究员'), (5, '讲师'), (6, '助理研究员'), (7, '医师'), (8, '主治医师'), (9, '副主任医师'), (10, '主任医师')], default=0)),
                ('degree', models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '博士'), (2, '硕士'), (3, '学士')], default=0)),
                ('position', models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '教职工'), (2, '学生')], default=0)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '在职'), (2, '离职'), (3, '在读'), (4, '毕业'), (5, '退学')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
