# Generated by Django 5.1.7 on 2025-05-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-user__date_joined']},
        ),
    ]
