# Generated by Django 5.1.7 on 2025-04-04 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(blank=True, default='', max_length=10)),
                ('long_id', models.CharField(blank=True, default='', max_length=40)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'FAILURE'), (1, 'SUCCESS'), (2, 'RUNNING'), (3, 'WAITING'), (4, 'STOPPED')], default=3)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('stopped', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(blank=True, default='', help_text='register number', max_length=15)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=0)),
                ('ethnicity', models.PositiveSmallIntegerField(choices=[(1, '汉族'), (2, '蒙古族'), (3, '回族'), (4, '藏族'), (5, '维吾尔族'), (6, '苗族'), (7, '彝族'), (8, '壮族'), (9, '布依族'), (10, '朝鲜族'), (11, '满族'), (12, '侗族'), (13, '瑶族'), (14, '白族'), (15, '土家族'), (16, '哈尼族'), (17, '哈萨克族'), (18, '傣族'), (19, '黎族'), (20, '傈僳族'), (21, '佤族'), (22, '畲族'), (23, '高山族'), (24, '拉祜族'), (25, '水族'), (26, '东乡族'), (27, '纳西族'), (28, '景颇族'), (29, '柯尔克孜族'), (30, '土族'), (31, '达斡尔族'), (32, '仫佬族'), (33, '羌族'), (34, '布朗族'), (35, '撒拉族'), (36, '毛南族'), (37, '仡佬族'), (38, '锡伯族'), (39, '阿昌族'), (40, '普米族'), (41, '塔吉克族'), (42, '怒族'), (43, '乌孜别克族'), (44, '俄罗斯族'), (45, '鄂温克族'), (46, '德昂族'), (47, '保安族'), (48, '裕固族'), (49, '京族'), (50, '塔塔尔族'), (51, '独龙族'), (52, '鄂伦春族'), (53, '赫哲族'), (54, '门巴族'), (55, '珞巴族'), (56, '基诺族'), (0, '其他')], default=1)),
                ('age', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, help_text='kg', null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='cm', null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('tissue', models.CharField(blank=True, default='', max_length=30)),
                ('first', models.CharField(help_text='file one', max_length=200)),
                ('second', models.CharField(blank=True, default='', help_text='file two', max_length=200)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'WES'), (2, 'WGS'), (0, '其他')], default=0)),
                ('platform', models.CharField(blank=True, default='', max_length=100)),
                ('comment', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hdbase.patient')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SocketTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hdbase.task')),
            ],
            bases=('hdbase.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdbase.dataset'),
        ),
    ]
