# Generated by Django 5.1.7 on 2025-04-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0002_dataset_name_alter_dataset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='command',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Call SNPs for WES'), (0, 'Run test task')], default=0),
        ),
    ]
