# Generated by Django 5.1.7 on 2025-05-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0003_task_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('values', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='command',
            field=models.PositiveSmallIntegerField(choices=[(1, '全外显子组分析'), (0, '模拟任务测试')], default=0),
        ),
        migrations.DeleteModel(
            name='SocketTask',
        ),
    ]
