# Generated by Django 5.1.7 on 2025-05-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0004_option_alter_task_command_delete_sockettask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
