# Generated by Django 5.1.7 on 2025-05-11 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0005_alter_option_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(blank=True, default='', max_length=10)),
                ('long_id', models.CharField(blank=True, default='', max_length=40)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('command', models.PositiveSmallIntegerField(choices=[(1, '全外显子组分析'), (0, '模拟任务测试')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'FAILURE'), (1, 'SUCCESS'), (2, 'RUNNING'), (3, 'WAITING'), (4, 'STOPPED')], default=3)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('stopped', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdbase.dataset')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
