# Generated by Django 5.1.7 on 2025-06-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0007_remove_patient_age_patient_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='cardiomyopathybloodroutine',
            name='tested',
            field=models.DateField(blank=True, help_text='检验时间', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathybloodroutine',
            name='alt',
            field=models.FloatField(blank=True, help_text='ALT (U/L)', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathybloodroutine',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloods', to='hdbase.cardiomyopathydisease'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathydisease',
            name='patient',
            field=models.ForeignKey(help_text='患者', on_delete=django.db.models.deletion.CASCADE, to='hdbase.patient'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecgs', to='hdbase.cardiomyopathydisease'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathygenemutation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genes', to='hdbase.cardiomyopathygenereport'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathygenereport',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hdbase.cardiomyopathydisease'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathymarker',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='hdbase.cardiomyopathydisease'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathymri',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mris', to='hdbase.cardiomyopathydisease'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathytreatment',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='hdbase.cardiomyopathydisease'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyultrasound',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasounds', to='hdbase.cardiomyopathydisease'),
        ),
    ]
