# Generated by Django 5.1.7 on 2025-06-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0008_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiomyopathyultrasound',
            name='dicom',
        ),
        migrations.AddField(
            model_name='cardiomyopathyultrasound',
            name='dicom_file',
            field=models.FileField(blank=True, help_text='影像文件', max_length=255, null=True, upload_to='dicom/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='cardiomyopathyultrasound',
            name='dicom_uuid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cardiomyopathyultrasound',
            name='lvedd_z',
            field=models.FloatField(blank=True, help_text='Z值', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathyultrasound',
            name='lvesd_z',
            field=models.FloatField(blank=True, help_text='Z值', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathytreatment',
            name='drugs',
            field=models.JSONField(blank=True, default=dict, help_text='治疗情况'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyultrasound',
            name='diagnosis',
            field=models.CharField(blank=True, default='', help_text='超声诊断', max_length=255),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyultrasound',
            name='report',
            field=models.FileField(blank=True, help_text='报告文件', max_length=200, null=True, upload_to='report/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyultrasound',
            name='tested',
            field=models.DateField(blank=True, help_text='检查时间', null=True),
        ),
    ]
