# Generated by Django 5.1.7 on 2025-06-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0009_remove_cardiomyopathyultrasound_dicom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiomyopathymri',
            name='dicom',
        ),
        migrations.AddField(
            model_name='cardiomyopathymri',
            name='dicom_file',
            field=models.FileField(blank=True, help_text='影像文件', max_length=255, null=True, upload_to='dicom/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='cardiomyopathymri',
            name='dicom_uuid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cardiomyopathymri',
            name='lge',
            field=models.PositiveSmallIntegerField(choices=[(0, '阴性'), (1, '阳性')], default=0, help_text='LGE'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathymri',
            name='report',
            field=models.FileField(blank=True, help_text='报告文件', max_length=200, null=True, upload_to='report/%Y/%m/'),
        ),
    ]
