# Generated by Django 5.1.7 on 2025-06-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0010_remove_cardiomyopathymri_dicom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiomyopathygenemutation',
            name='acmg',
            field=models.CharField(blank=True, default='', help_text='ACMG变异评级', max_length=30),
        ),
        migrations.AlterField(
            model_name='cardiomyopathygenemutation',
            name='gmode',
            field=models.CharField(blank=True, default='', help_text='遗传模式', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardiomyopathygenemutation',
            name='mutation',
            field=models.CharField(blank=True, default='', help_text='突变信息', max_length=80),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default='', help_text='地址', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(blank=True, help_text='出生日期', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.PositiveSmallIntegerField(choices=[(1, '汉族'), (2, '蒙古族'), (3, '回族'), (4, '藏族'), (5, '维吾尔族'), (6, '苗族'), (7, '彝族'), (8, '壮族'), (9, '布依族'), (10, '朝鲜族'), (11, '满族'), (12, '侗族'), (13, '瑶族'), (14, '白族'), (15, '土家族'), (16, '哈尼族'), (17, '哈萨克族'), (18, '傣族'), (19, '黎族'), (20, '傈僳族'), (21, '佤族'), (22, '畲族'), (23, '高山族'), (24, '拉祜族'), (25, '水族'), (26, '东乡族'), (27, '纳西族'), (28, '景颇族'), (29, '柯尔克孜族'), (30, '土族'), (31, '达斡尔族'), (32, '仫佬族'), (33, '羌族'), (34, '布朗族'), (35, '撒拉族'), (36, '毛南族'), (37, '仡佬族'), (38, '锡伯族'), (39, '阿昌族'), (40, '普米族'), (41, '塔吉克族'), (42, '怒族'), (43, '乌孜别克族'), (44, '俄罗斯族'), (45, '鄂温克族'), (46, '德昂族'), (47, '保安族'), (48, '裕固族'), (49, '京族'), (50, '塔塔尔族'), (51, '独龙族'), (52, '鄂伦春族'), (53, '赫哲族'), (54, '门巴族'), (55, '珞巴族'), (56, '基诺族'), (0, '其他')], default=1, help_text='民族'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=0, help_text='性别'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='身高(cm)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(help_text='名字', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.CharField(blank=True, default='', help_text='登记号', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='电话', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True, help_text='休重(Kg)', null=True),
        ),
    ]
