# Generated by Django 5.1.7 on 2025-06-25 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0012_cardiomyopathygenemutation_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kawasakidisease',
            name='disease_code',
            field=models.CharField(blank=True, default='', help_text='编号或测序编号', max_length=100),
        ),
        migrations.AlterField(
            model_name='kawasakidisease',
            name='cqlx',
            field=models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '完全'), (2, '不完全')], default=0, help_text='川崎类型'),
        ),
        migrations.AlterField(
            model_name='kawasakidisease',
            name='patient',
            field=models.ForeignKey(help_text='患者', on_delete=django.db.models.deletion.CASCADE, to='hdbase.patient'),
        ),
    ]
