# Generated by Django 5.1.7 on 2025-06-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0014_kawasakigenemutation_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrhythmiadisease',
            name='disease_code',
            field=models.CharField(blank=True, default='', help_text='编号或测序编号', max_length=100),
        ),
    ]
