# Generated by Django 5.1.7 on 2025-06-30 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0016_remove_radiofrequencyablation_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiomyopathydisease',
            name='code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='congenitalintervenecardiogram',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardiograms', to='hdbase.congenitalintervenedisease'),
        ),
        migrations.AlterField(
            model_name='congenitalsurgerypreexamine',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preexamines', to='hdbase.congenitalsurgerydisease'),
        ),
    ]
