# Generated by Django 5.1.7 on 2025-06-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0017_cardiomyopathydisease_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrhythmiadisease',
            name='code',
            field=models.CharField(blank=True, default='', help_text='编号', max_length=12),
        ),
        migrations.AddField(
            model_name='congenitalintervenedisease',
            name='code',
            field=models.CharField(blank=True, default='', help_text='编号', max_length=12),
        ),
        migrations.AddField(
            model_name='congenitalsurgerydisease',
            name='code',
            field=models.CharField(blank=True, default='', help_text='编号', max_length=12),
        ),
        migrations.AddField(
            model_name='kawasakidisease',
            name='code',
            field=models.CharField(blank=True, default='', help_text='编号', max_length=12),
        ),
        migrations.AlterField(
            model_name='cardiomyopathydisease',
            name='disease_code',
            field=models.CharField(blank=True, default='', help_text='测序编号', max_length=100),
        ),
        migrations.AlterField(
            model_name='kawasakidisease',
            name='disease_code',
            field=models.CharField(blank=True, default='', help_text='测序编号', max_length=100),
        ),
    ]
