# Generated by Django 5.1.7 on 2025-08-12 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0018_arrhythmiadisease_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiomyopathydisease',
            name='code',
            field=models.CharField(blank=True, default='', help_text='编号', max_length=12),
        ),
        migrations.CreateModel(
            name='DiseaseImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.PositiveSmallIntegerField(choices=[(1, '心肌病'), (2, '川崎病'), (3, '心律失常'), (4, '先心病-外科'), (5, '先心病-VSD介入')], default=1, help_text='疾病类型')),
                ('excel', models.FileField(help_text='上传文件', max_length=200, upload_to='excels/%Y/%m/')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'FAILURE'), (1, 'SUCCESS'), (2, 'RUNNING'), (3, 'WAITING')], default=3)),
                ('message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
