# Generated by Django 5.1.7 on 2025-08-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0019_alter_cardiomyopathydisease_code_diseaseimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.FloatField(blank=True, help_text='身高(cm)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(help_text='姓名', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.CharField(help_text='登记号', max_length=15, unique=True),
        ),
    ]
