# Generated by Django 5.1.7 on 2025-08-30 14:40

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0020_alter_patient_height_alter_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiomyopathyecg',
            name='cdzzlx',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '无'), (1, '窦房阻滞'), (2, '房室阻滞'), (3, '室内阻滞')], help_text='传导阻滞类型', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathyecg',
            name='fxxlsc',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '无'), (1, '房早'), (2, '房速'), (3, '房扑'), (4, '房颤')], help_text='房性心律失常类型', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathyecg',
            name='pms',
            field=models.FloatField(blank=True, help_text='P(ms)', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathyecg',
            name='pr',
            field=models.FloatField(blank=True, help_text='P-R(ms)', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathyecg',
            name='qrs',
            field=models.FloatField(blank=True, help_text='QRS(ms)', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathyecg',
            name='qtc',
            field=models.FloatField(blank=True, help_text='QTc', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathyecg',
            name='rv5_sv1',
            field=models.FloatField(blank=True, help_text='RV5/SV1(mv)', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathyecg',
            name='rv5sv1',
            field=models.FloatField(blank=True, help_text='Rv5+Sv1(mv)', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathyecg',
            name='sxxlsc',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '无'), (1, '室早'), (2, '室速'), (3, '室扑'), (4, '室颤')], help_text='室性心律失常类型', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathyecg',
            name='xsl',
            field=models.FloatField(blank=True, help_text='心室率(bpm)', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathymarker',
            name='bnpjysj',
            field=models.DateField(blank=True, help_text='BNP检验时间', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathymarker',
            name='ntbnpjysj',
            field=models.DateField(blank=True, help_text='NT-BNP检验时间', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathytreatment',
            name='eglj',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '无'), (1, '有')], help_text='恩格列净', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathytreatment',
            name='lnj',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '氢氯噻嗪'), (2, '螺内酯'), (3, '呋噻米'), (4, '其他')], help_text='利尿剂', max_length=7),
        ),
        migrations.AlterField(
            model_name='cardiomyopathydisease',
            name='complication',
            field=models.CharField(blank=True, default='', help_text='合并症', max_length=80),
        ),
        migrations.AlterField(
            model_name='cardiomyopathydisease',
            name='disease_type',
            field=models.CharField(blank=True, choices=[('DCM', '扩张型心肌病'), ('HCM', '肥厚型心肌病'), ('RCM', '限制型心肌病'), ('ARVC', '致心律失常性心肌病'), ('NDLVC', '非扩张型心肌病'), ('Other', '其他类型心肌病'), ('Unknown', '未知')], default='Unknown', help_text='心肌病分型', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardiomyopathydisease',
            name='special_treatment',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, 'PAB'), (2, 'VAD'), (3, 'CRT'), (4, 'ICD'), (5, '起搏器'), (6, '射频消融'), (7, '心脏移植'), (8, '其他')], default=0, help_text='特殊治疗'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='age',
            field=models.CharField(blank=True, help_text='做心电图时年龄', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='cdzz',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='传导阻滞', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='dxdgh',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='窦性心动过缓', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='dxdgs',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='窦性心动过速', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='fxdgs',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='房性心动过速', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='fxzb',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='房性早搏', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='stt',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='ST-T改变', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='sxdgs',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='室性心动过速', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='sxzb',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='室性早搏', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='xfcd',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='心房颤动', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='ycqb',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='异常Q波', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='zffd',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='左房肥大', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyecg',
            name='zsfd',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '是')], help_text='左室肥大', null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathymri',
            name='dema',
            field=models.PositiveSmallIntegerField(choices=[(0, '阴性'), (1, '阳性'), (2, '可疑')], default=0, help_text='心肌水肿'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathymri',
            name='lge',
            field=models.PositiveSmallIntegerField(choices=[(0, '阴性'), (1, '阳性'), (2, '可疑')], default=0, help_text='LGE'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathymri',
            name='microcirculation',
            field=models.PositiveSmallIntegerField(choices=[(0, '阴性'), (1, '阳性'), (2, '可疑')], default=0, help_text='心肌微循环'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathymri',
            name='perfusion',
            field=models.PositiveSmallIntegerField(choices=[(0, '阴性'), (1, '阳性'), (2, '可疑')], default=0, help_text='首过灌注'),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyultrasound',
            name='age',
            field=models.CharField(blank=True, default='', help_text='做超声时年龄(岁)', max_length=15),
        ),
    ]
