# Generated by Django 5.1.7 on 2025-08-31 15:12

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0021_cardiomyopathyecg_cdzzlx_cardiomyopathyecg_fxxlsc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiomyopathytreatment',
            name='aceiarni',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', '无'), ('1', '卡托普利'), ('2', '依那普利'), ('3', '诺欣妥')], help_text='ACEI或ARNI', max_length=7),
        ),
        migrations.AddField(
            model_name='cardiomyopathytreatment',
            name='bstzdj',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', '无'), ('1', '美托洛尔'), ('2', '其他')], help_text='B受体阻断剂', max_length=5),
        ),
        migrations.AddField(
            model_name='cardiomyopathytreatment',
            name='kxlsc',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '无'), (1, '有')], help_text='抗心律失常', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathytreatment',
            name='qtyw',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', '无'), ('1', '地高辛'), ('2', '伊伐布雷定'), ('3', '唯立西呱'), ('4', '其他')], help_text='其他药物', max_length=9),
        ),
        migrations.AlterField(
            model_name='cardiomyopathytreatment',
            name='lnj',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', '无'), ('1', '氢氯噻嗪'), ('2', '螺内酯'), ('3', '呋噻米'), ('4', '其他')], help_text='利尿剂', max_length=9),
        ),
    ]
