# Generated by Django 5.1.7 on 2025-09-01 08:12

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0022_cardiomyopathytreatment_aceiarni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiomyopathytreatment',
            name='drugs',
        ),
        migrations.RemoveField(
            model_name='cardiomyopathytreatment',
            name='treated',
        ),
        migrations.AddField(
            model_name='cardiomyopathytreatment',
            name='kbkn',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '无'), (1, '有')], help_text='抗板或抗凝', null=True),
        ),
        migrations.AddField(
            model_name='cardiomyopathytreatment',
            name='tszl',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', '无'), ('1', 'PAB'), ('2', 'VAD'), ('3', 'CRT'), ('4', 'ICD'), ('5', '起搏器'), ('6', '射频消融'), ('7', '心脏移植'), ('8', '其他')], help_text='特殊治疗', max_length=17),
        ),
        migrations.AlterField(
            model_name='cardiomyopathydisease',
            name='disease_type',
            field=models.CharField(blank=True, choices=[('EFE', '心内膜弹力纤维增生症'), ('DCM', '扩张型心肌病'), ('HCM', '肥厚型心肌病'), ('RCM', '限制型心肌病'), ('IMCM', '遗传代谢性心肌病'), ('ARVC', '致心律失常性心肌病'), ('NDLVC', '非扩张型心肌病'), ('Other', '其他类型心肌病'), ('Unknown', '未知')], default='Unknown', help_text='心肌病分型', max_length=10),
        ),
    ]
