# Generated by Django 5.1.7 on 2025-09-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0023_remove_cardiomyopathytreatment_drugs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiomyopathydisease',
            name='disease_type',
            field=models.CharField(blank=True, choices=[('EFE', '心内膜弹力纤维增生症'), ('DCM', '扩张型心肌病'), ('HCM', '肥厚型心肌病'), ('RCM', '限制型心肌病'), ('SCM', '继发性心肌病'), ('MDCM', '肌营养不良型心肌病'), ('IMCM', '遗传代谢性心肌病'), ('ARVC', '致心律失常性心肌病'), ('NDLVC', '非扩张型心肌病'), ('Other', '其他类型心肌病'), ('Unknown', '未知')], default='Unknown', help_text='心肌病分型', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardiomyopathydisease',
            name='hospital_visits',
            field=models.SmallIntegerField(blank=True, help_text='心衰再入院次数', null=True),
        ),
    ]
