# Generated by Django 5.1.7 on 2025-09-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0024_alter_cardiomyopathydisease_disease_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiomyopathyultrasound',
            name='lvedd_z',
            field=models.CharField(blank=True, help_text='Z值', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardiomyopathyultrasound',
            name='lvesd_z',
            field=models.CharField(blank=True, help_text='Z值', max_length=10, null=True),
        ),
    ]
