# Generated by Django 5.1.7 on 2025-09-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0025_alter_cardiomyopathyultrasound_lvedd_z_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiomyopathydisease',
            name='code',
        ),
    ]
