# Generated by Django 5.1.7 on 2025-09-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdbase', '0026_remove_cardiomyopathydisease_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
    ]
