from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
	path('', index, name='index'),
	path('aboutus', aboutus, name='aboutus'),
	path('changelog', changelog, name='changelog'),
	path('validate', validate_field, name='valid-field'),
	path('upload', upload_process, name='upload-file'),
	path('browser', FileBrowseView.as_view(), name='file-browser'),
	path('select', fetch_for_select, name='fetch-select'),
	path('tasks', TaskListView.as_view(), name='list-tasks'),
	path('task/add', TaskCreateView.as_view(), name='add-task'),
	path('patients', PatientListView.as_view(), name='list-patients'),
	path('patient/add', PatientCreateView.as_view(), name='add-patient'),
	path('patient/edit/<int:pk>', PatientUpdateView.as_view(), name='edit-patient'),
	path('patient/delete/<int:pk>', PatientDeleteView.as_view(), name='delete-patient'),
	path('datasets', DatasetListView.as_view(), name='list-datasets'),
	path('dataset/add', DatasetCreateView.as_view(), name='add-dataset'),
	path('setting/website', WebsiteSettingView.as_view(), name='setting-website'),
	path('setting/global', GlobalSettingView.as_view(), name='setting-global'),
	path('setting/parameter', ParameterSettingView.as_view(), name='setting-parameter'),
	path('cardiomyopathy', CardiomyopathyListView.as_view(), name='list-cardiomyopathy'),
	path('cardiomyopathy/add', CardiomyopathyCreateView.as_view(), name='add-cardiomyopathy'),
	path('cardiomyopathy/view/<int:pk>', CardiomyopathyDetailView.as_view(), name='view-cardiomyopathy'),
	path('cardiomyopathy/edit/<int:pk>', CardiomyopathyUpdateView.as_view(), name='edit-cardiomyopathy'),
	path('cardiomyopathy/delete/<int:pk>', CardiomyopathyDeleteView.as_view(), name='delete-cardiomyopathy'),
	path('cardiomyopathy/<int:did>/examine/add', CardiomyopathyBloodCreateView.as_view(), name='add-cardiomyopathy-examine'),
	path('cardiomyopathy/<int:did>/examine/edit/<int:pk>', CardiomyopathyBloodUpdateView.as_view(), name='edit-cardiomyopathy-examine'),
	path('cardiomyopathy/<int:did>/examine/delete/<int:pk>', CardiomyopathyBloodDeleteView.as_view(), name='delete-cardiomyopathy-examine'),
	path('cardiomyopathy/<int:did>/marker/add', CardiomyopathyMarkerCreateView.as_view(), name='add-cardiomyopathy-marker'),
	path('cardiomyopathy/<int:did>/marker/edit/<int:pk>', CardiomyopathyMarkerUpdateView.as_view(), name='edit-cardiomyopathy-marker'),
	path('cardiomyopathy/<int:did>/marker/delete/<int:pk>', CardiomyopathyMarkerDeleteView.as_view(), name='delete-cardiomyopathy-marker'),
	path('cardiomyopathy/<int:did>/treatment/add', CardiomyopathyTreatmentCreateView.as_view(), name='add-cardiomyopathy-treatment'),
	path('cardiomyopathy/<int:did>/treatment/edit/<int:pk>', CardiomyopathyTreatmentUpdateView.as_view(), name='edit-cardiomyopathy-treatment'),
	path('cardiomyopathy/<int:did>/treatment/delete/<int:pk>', CardiomyopathyTreatmentDeleteView.as_view(), name='delete-cardiomyopathy-treatment'),
	path('cardiomyopathy/<int:did>/ultrasound/add', CardiomyopathyUltrasoundCreateView.as_view(), name='add-cardiomyopathy-ultrasound'),
	path('cardiomyopathy/<int:did>/ultrasound/edit/<int:pk>', CardiomyopathyUltrasoundUpdateView.as_view(), name='edit-cardiomyopathy-ultrasound'),
	path('cardiomyopathy/<int:did>/ultrasound/delete/<int:pk>', CardiomyopathyUltrasoundDeleteView.as_view(), name='delete-cardiomyopathy-ultrasound'),
	path('cardiomyopathy/<int:did>/mri/add', CardiomyopathyMRICreateView.as_view(), name='add-cardiomyopathy-mri'),
	path('cardiomyopathy/<int:did>/mri/edit/<int:pk>', CardiomyopathyMRIUpdateView.as_view(), name='edit-cardiomyopathy-mri'),
	path('cardiomyopathy/<int:did>/mri/delete/<int:pk>', CardiomyopathyMRIDeleteView.as_view(), name='delete-cardiomyopathy-mri'),
	path('cardiomyopathy/<int:did>/ecg/add', CardiomyopathyECGCreateView.as_view(), name='add-cardiomyopathy-ecg'),
	path('cardiomyopathy/<int:did>/ecg/edit/<int:pk>', CardiomyopathyECGUpdateView.as_view(), name='edit-cardiomyopathy-ecg'),
	path('cardiomyopathy/<int:did>/ecg/delete/<int:pk>', CardiomyopathyECGDeleteView.as_view(), name='delete-cardiomyopathy-ecg'),
	path('cardiomyopathy/<int:did>/genereport/add', CardiomyopathyGeneReportCreateView.as_view(), name='add-cardiomyopathy-greport'),
	path('cardiomyopathy/<int:did>/genereport/edit/<int:pk>', CardiomyopathyGeneReportUpdateView.as_view(), name='edit-cardiomyopathy-greport'),
	path('cardiomyopathy/<int:did>/genereport/delete/<int:pk>', CardiomyopathyGeneReportDeleteView.as_view(), name='delete-cardiomyopathy-greport'),
	path('cardiomyopathy/<int:did>/genemutation/add', CardiomyopathyGeneMutationCreateView.as_view(), name='add-cardiomyopathy-gmutation'),
	path('cardiomyopathy/<int:did>/genemutation/edit/<int:pk>', CardiomyopathyGeneMutationUpdateView.as_view(), name='edit-cardiomyopathy-gmutation'),
	path('cardiomyopathy/<int:did>/genemutation/delete/<int:pk>', CardiomyopathyGeneMutationDeleteView.as_view(), name='delete-cardiomyopathy-gmutation'),

]
