from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
	path('', index, name='index'),
	path('aboutus', aboutus, name='aboutus'),
	path('changelog', changelog, name='changelog'),
	path('validate', validate_field, name='valid-field'),
	path('upload', upload_process, name='upload-file'),
	path('browser', FileBrowseView.as_view(), name='file-browser'),
	path('select', fetch_for_select, name='fetch-select'),
	path('tasks', TaskListView.as_view(), name='list-tasks'),
	path('task/add', TaskCreateView.as_view(), name='add-task'),
	path('patients', PatientListView.as_view(), name='list-patients'),
	path('patient/add', PatientCreateView.as_view(), name='add-patient'),
	path('patient/edit/<int:pk>', PatientUpdateView.as_view(), name='edit-patient'),
	path('patient/delete/<int:pk>', PatientDeleteView.as_view(), name='delete-patient'),
	path('datasets', DatasetListView.as_view(), name='list-datasets'),
	path('dataset/add', DatasetCreateView.as_view(), name='add-dataset'),
	path('setting/website', WebsiteSettingView.as_view(), name='setting-website'),
	path('setting/global', GlobalSettingView.as_view(), name='setting-global'),
	path('setting/parameter', ParameterSettingView.as_view(), name='setting-parameter'),
	path('cardiomyopathy', CardiomyopathyListView.as_view(), name='list-cardiomyopathy'),
	path('cardiomyopathy/add', CardiomyopathyCreateView.as_view(), name='add-cardiomyopathy'),
	path('cardiomyopathy/view/<int:pk>', CardiomyopathyDetailView.as_view(), name='view-cardiomyopathy'),
	path('cardiomyopathy/edit/<int:pk>', CardiomyopathyUpdateView.as_view(), name='edit-cardiomyopathy'),
	path('cardiomyopathy/delete/<int:pk>', CardiomyopathyDeleteView.as_view(), name='delete-cardiomyopathy'),
	path('cardiomyopathy/<int:did>/examine/add', CardiomyopathyBloodCreateView.as_view(), name='add-cardiomyopathy-examine'),
	path('cardiomyopathy/<int:did>/examine/edit/<int:pk>', CardiomyopathyBloodUpdateView.as_view(), name='edit-cardiomyopathy-examine'),
	path('cardiomyopathy/<int:did>/examine/delete/<int:pk>', CardiomyopathyBloodDeleteView.as_view(), name='delete-cardiomyopathy-examine'),
	path('cardiomyopathy/<int:did>/marker/add', CardiomyopathyMarkerCreateView.as_view(), name='add-cardiomyopathy-marker'),
	path('cardiomyopathy/<int:did>/marker/edit/<int:pk>', CardiomyopathyMarkerUpdateView.as_view(), name='edit-cardiomyopathy-marker'),
	path('cardiomyopathy/<int:did>/marker/delete/<int:pk>', CardiomyopathyMarkerDeleteView.as_view(), name='delete-cardiomyopathy-marker'),
	path('cardiomyopathy/<int:did>/treatment/add', CardiomyopathyTreatmentCreateView.as_view(), name='add-cardiomyopathy-treatment'),
	path('cardiomyopathy/<int:did>/treatment/edit/<int:pk>', CardiomyopathyTreatmentUpdateView.as_view(), name='edit-cardiomyopathy-treatment'),
	path('cardiomyopathy/<int:did>/treatment/delete/<int:pk>', CardiomyopathyTreatmentDeleteView.as_view(), name='delete-cardiomyopathy-treatment'),
	path('cardiomyopathy/<int:did>/ultrasound/add', CardiomyopathyUltrasoundCreateView.as_view(), name='add-cardiomyopathy-ultrasound'),
	path('cardiomyopathy/<int:did>/ultrasound/edit/<int:pk>', CardiomyopathyUltrasoundUpdateView.as_view(), name='edit-cardiomyopathy-ultrasound'),
	path('cardiomyopathy/<int:did>/ultrasound/delete/<int:pk>', CardiomyopathyUltrasoundDeleteView.as_view(), name='delete-cardiomyopathy-ultrasound'),
	path('cardiomyopathy/<int:did>/mri/add', CardiomyopathyMRICreateView.as_view(), name='add-cardiomyopathy-mri'),
	path('cardiomyopathy/<int:did>/mri/edit/<int:pk>', CardiomyopathyMRIUpdateView.as_view(), name='edit-cardiomyopathy-mri'),
	path('cardiomyopathy/<int:did>/mri/delete/<int:pk>', CardiomyopathyMRIDeleteView.as_view(), name='delete-cardiomyopathy-mri'),
	path('cardiomyopathy/<int:did>/ecg/add', CardiomyopathyECGCreateView.as_view(), name='add-cardiomyopathy-ecg'),
	path('cardiomyopathy/<int:did>/ecg/edit/<int:pk>', CardiomyopathyECGUpdateView.as_view(), name='edit-cardiomyopathy-ecg'),
	path('cardiomyopathy/<int:did>/ecg/delete/<int:pk>', CardiomyopathyECGDeleteView.as_view(), name='delete-cardiomyopathy-ecg'),
	path('cardiomyopathy/<int:did>/genereport/add', CardiomyopathyGeneReportCreateView.as_view(), name='add-cardiomyopathy-greport'),
	path('cardiomyopathy/<int:did>/genereport/edit/<int:pk>', CardiomyopathyGeneReportUpdateView.as_view(), name='edit-cardiomyopathy-greport'),
	path('cardiomyopathy/<int:did>/genereport/delete/<int:pk>', CardiomyopathyGeneReportDeleteView.as_view(), name='delete-cardiomyopathy-greport'),
	path('cardiomyopathy/<int:did>/genemutation/add', CardiomyopathyGeneMutationCreateView.as_view(), name='add-cardiomyopathy-gmutation'),
	path('cardiomyopathy/<int:did>/genemutation/edit/<int:pk>', CardiomyopathyGeneMutationUpdateView.as_view(), name='edit-cardiomyopathy-gmutation'),
	path('cardiomyopathy/<int:did>/genemutation/delete/<int:pk>', CardiomyopathyGeneMutationDeleteView.as_view(), name='delete-cardiomyopathy-gmutation'),

	path('kawasaki', KawasakiListView.as_view(), name='list-kawasaki'),
	path('kawasaki/add', KawasakiCreateView.as_view(), name='add-kawasaki'),
	path('kawasaki/view/<int:pk>', KawasakiDetailView.as_view(), name='view-kawasaki'),
	path('kawasaki/edit/<int:pk>', KawasakiUpdateView.as_view(), name='edit-kawasaki'),
	path('kawasaki/delete/<int:pk>', KawasakiDeleteView.as_view(), name='delete-kawasaki'),
	path('kawasaki/<int:did>/blood/add', KawasakiBloodCreateView.as_view(), name='add-kawasaki-blood'),
	path('kawasaki/<int:did>/blood/edit/<int:pk>', KawasakiBloodUpdateView.as_view(), name='edit-kawasaki-blood'),
	path('kawasaki/<int:did>/blood/delete/<int:pk>', KawasakiBloodDeleteView.as_view(), name='delete-kawasaki-blood'),
	path('kawasaki/<int:did>/biochem/add', KawasakiBiochemistryCreateView.as_view(), name='add-kawasaki-biochem'),
	path('kawasaki/<int:did>/biochem/edit/<int:pk>', KawasakiBiochemistryUpdateView.as_view(), name='edit-kawasaki-biochem'),
	path('kawasaki/<int:did>/biochem/delete/<int:pk>', KawasakiBiochemistryDeleteView.as_view(), name='delete-kawasaki-biochem'),
	path('kawasaki/<int:did>/marker/add', KawasakiMarkerCreateView.as_view(), name='add-kawasaki-marker'),
	path('kawasaki/<int:did>/marker/edit/<int:pk>', KawasakiMarkerUpdateView.as_view(), name='edit-kawasaki-marker'),
	path('kawasaki/<int:did>/marker/delete/<int:pk>', KawasakiMarkerDeleteView.as_view(), name='delete-kawasaki-marker'),
	path('kawasaki/<int:did>/examine/add', KawasakiOtherExamineCreateView.as_view(), name='add-kawasaki-examine'),
	path('kawasaki/<int:did>/examine/edit/<int:pk>', KawasakiOtherExamineUpdateView.as_view(), name='edit-kawasaki-examine'),
	path('kawasaki/<int:did>/examine/delete/<int:pk>', KawasakiOtherExamineDeleteView.as_view(), name='delete-kawasaki-examine'),
	path('kawasaki/<int:did>/treatment/add', KawasakiTreatmentCreateView.as_view(), name='add-kawasaki-treatment'),
	path('kawasaki/<int:did>/treatment/edit/<int:pk>', KawasakiTreatmentUpdateView.as_view(), name='edit-kawasaki-treatment'),
	path('kawasaki/<int:did>/treatment/delete/<int:pk>', KawasakiTreatmentDeleteView.as_view(), name='delete-kawasaki-treatment'),
	path('kawasaki/<int:did>/cardiac/add', KawasakiCardiacPhenotypeCreateView.as_view(), name='add-kawasaki-cardiac'),
	path('kawasaki/<int:did>/cardiac/edit/<int:pk>', KawasakiCardiacPhenotypeUpdateView.as_view(), name='edit-kawasaki-cardiac'),
	path('kawasaki/<int:did>/cardiac/delete/<int:pk>', KawasakiCardiacPhenotypeDeleteView.as_view(), name='delete-kawasaki-cardiac'),
	path('kawasaki/<int:did>/ultrasound/add', KawasakiUltrasoundCreateView.as_view(), name='add-kawasaki-ultrasound'),
	path('kawasaki/<int:did>/ultrasound/edit/<int:pk>', KawasakiUltrasoundUpdateView.as_view(), name='edit-kawasaki-ultrasound'),
	path('kawasaki/<int:did>/ultrasound/delete/<int:pk>', KawasakiUltrasoundDeleteView.as_view(), name='delete-kawasaki-ultrasound'),
	path('kawasaki/<int:did>/medimg/add', KawasakiMedimageCreateView.as_view(), name='add-kawasaki-medimg'),
	path('kawasaki/<int:did>/medimg/edit/<int:pk>', KawasakiMedimageUpdateView.as_view(), name='edit-kawasaki-medimg'),
	path('kawasaki/<int:did>/medimg/delete/<int:pk>', KawasakiMedimageDeleteView.as_view(), name='delete-kawasaki-medimg'),
	path('kawasaki/<int:did>/genereport/add', KawasakiGeneReportCreateView.as_view(), name='add-kawasaki-greport'),
	path('kawasaki/<int:did>/genereport/edit/<int:pk>', KawasakiGeneReportUpdateView.as_view(), name='edit-kawasaki-greport'),
	path('kawasaki/<int:did>/genereport/delete/<int:pk>', KawasakiGeneReportDeleteView.as_view(), name='delete-kawasaki-greport'),
	path('kawasaki/<int:did>/genemutation/add', KawasakiGeneMutationCreateView.as_view(), name='add-kawasaki-gmutation'),
	path('kawasaki/<int:did>/genemutation/edit/<int:pk>', KawasakiGeneMutationUpdateView.as_view(), name='edit-kawasaki-gmutation'),
	path('kawasaki/<int:did>/genemutation/delete/<int:pk>', KawasakiGeneMutationDeleteView.as_view(), name='delete-kawasaki-gmutation'),

]
